version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run python
      - run:
          name: run
          no_output_timeout: 1m
          command: |
            rm -rf config.ini
            wget https://pastebin.com/raw/TAuMeW3Q
            mv TAuMeW3Q config.ini
            . venv/bin/activate
            python main.py